name: ReactApp-AWS-S3 CD

env:
  AWS_REGION: ap-south-1
  S3_BUCKECT_NAME: dev-ap-south-1-myagileboard
  CLOUDFRONT_DISTRIBUTION_ID: E2LKJW0PZN196Y # set this to your cloudfront distribution-id

# Run workflow only on push to main(dev) branch
on:
  push:
    branches: ['main']
  path-ignore:
    - '.eslintrc.json'
    - 'docs/**'
    - 'README.md'

jobs:
  build-react-my-agile-board:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - name: Checking out code
        uses: actions/checkout@v3

      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          DISABLE_ESLINT_PLUGIN: true
          REACT_APP_OKTA_CLIENT_ID: ${{ secrets.OKTA_CLIENT_ID }}
          REACT_APP_OCTA_DOMAIN: ${{ secrets.OCTA_DOMAIN }}
          BACKEND_DOMAIN_URL: ${{ secrets.BACKEND_DOMAIN_URL }}

      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Installing dependencies
        run: npm ci --production

      - name: Building project
        run: npm run build --production

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3 bucket
        run: aws s3 sync build/ s3://$S3_BUCKECT_NAME --delete

      - name: Clearing Cloudfront Cache
        run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
