name: ReactApp CI

env:
  REACT_APP_OKTA_CLIENT_ID: ${{ secrets.OKTA_CLIENT_ID }}
  REACT_APP_OCTA_DOMAIN: ${{ secrets.OCTA_DOMAIN }}
  BACKEND_DOMAIN_URL: ${{ secrets.BACKEND_DOMAIN_URL }}

on:
  pull_request:
    branches: [main]

jobs:
  test-react-app:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - name: Checking out code
        uses: actions/checkout@v3

      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Installing dependencies
        run: npm ci

      # - name: Building project just to check
      #   run: npm run build --if-present --production

      # - name: Testing project with coverage
      #   run: npm run test:coverage
